// <auto-generated />
using System;
using KucukkoyIHL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KIMDER.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KucukkoyIHL.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tüm mezunlarımızın bir araya geleceği muhteşem bir gece sizi bekliyor. Canlı müzik, yemek ve bol sohbet!",
                            EventDate = new DateTime(2025, 10, 15, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/mezunlar-gecesi.jpg",
                            IsActive = true,
                            Location = "Küçükköy AİHL Konferans Salonu",
                            Title = "Mezunlar Gecesi 2025"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 23, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Mezunlarımız için düzenlenen piknik ve spor aktiviteleri ile keyifli bir gün geçireceğiz.",
                            EventDate = new DateTime(2025, 11, 5, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/piknik.jpg",
                            IsActive = true,
                            Location = "Atatürk Parkı",
                            Title = "Piknik ve Spor Şenliği"
                        });
                });

            modelBuilder.Entity("KucukkoyIHL.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Sevgili mezunlarımız, 15 Ekim 2025 tarihinde okulumuzda düzenlenecek olan mezunlar buluşmasına hepinizi davet ediyoruz. Eski günleri anımsayacak, yeni dostluklar kuracağımız bu özel günde sizleri aramızda görmekten mutluluk duyacağız.",
                            CreatedDate = new DateTime(2025, 9, 25, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/mezunlar-bulusma.jpg",
                            IsActive = true,
                            Title = "Mezunlar Buluşması 2025"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Küçükköy Anadolu İmam Hatip Lisesi olarak 25. yılımızı kutluyoruz! Bu gurur verici yıldönümünde tüm mezunlarımızı ve ailelerini kutlama etkinliğimize bekliyoruz.",
                            CreatedDate = new DateTime(2025, 9, 20, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "/images/yildonumu.jpg",
                            IsActive = true,
                            Title = "Okul Yıldönümü Kutlaması"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
